/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.31
 * Generated at: 2020-06-28 10:35:50 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import smartInterface.models.Switch;
import smartInterface.models.Controller;

public final class homePage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("smartInterface.models.Switch");
    _jspx_imports_classes.add("smartInterface.models.Controller");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"it\">\n");
      out.write("\t<head>\n");
      out.write("\t\t<meta charset=\"UTF-8\">\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"style.css\" type=\"text/css\" >\n");
      out.write("\t\t<title>ARDUINO_HOME_CONTROLLER</title>\n");
      out.write("\t</head>\n");
      out.write("\t<body>\n");
      out.write("\t\t<br><br>\n");
      out.write("\t\t<h1 align= \"center\" style=\"color: white;\">~");
      out.print(Controller.getName().toUpperCase());
      out.write("~</h1>\n");
      out.write("\t\t<h3 align= \"center\" style=\"color: white; font-style: italic\">Gestisci i tuoi dispositivi!</h3>\n");
      out.write("\t\t<br><br>\n");
      out.write("\t\t<br><br>\n");
      out.write("\t\t<div align=\"center\" id=\"container\">\n");
      out.write("\t\t\t<form action=\"switch1IO\" method =\"post\">\n");
      out.write("\t\t\t\t<b><label style=\"color:white\">SWITCH 1: </label></b>\n");
      out.write("\t\t\t\t");
 if(Controller.getSwitch1().withName()==0) { 
      out.write("\n");
      out.write("\t\t\t\t\t<input type=\"text\" autocomplete=\"off\" name=\"sw1\" required>\n");
      out.write("\t\t\t\t\t<input type=\"submit\" value=\"ASSEGNA\" formaction=\"rinomina1\" formmethod=\"post\">\n");
      out.write("\t\t\t\t\t<input type=\"submit\" value=\"On/Off\" disabled>\n");
      out.write("\t\t\t \t\t<input type=\"submit\" value=\"DIMMER+\" disabled>\t\t\n");
      out.write("\t\t\t \t\t<input type=\"submit\" value=\"DIMMER-\" disabled>\n");
      out.write("\t\t\t \t\t<input type=\"submit\" value=\"RINOMINA\" disabled>\n");
      out.write("\t\t\t \t\t\n");
      out.write("\t\t\t \t");
 }else{ 
      out.write("\n");
      out.write("\t\t\t \t\t<label style=\"color: orange; font-weight: bold; font-style: italic;\">");
      out.print( Controller.getSwitch1().getName().toUpperCase() );
      out.write("</label>\n");
      out.write("\t\t\t\t\t<input type=\"submit\" value=\"ASSEGNA\" disabled>\n");
      out.write("\t\t\t\t\t");
 if(Controller.getSwitch1().getStatus()==0) { 
      out.write("\n");
      out.write("\t\t\t\t\t\t<input type=\"submit\" value=\"ACCENDI\" formmethod=\"post\" style=\"color: darkgreen\">\n");
      out.write("\t\t\t\t\t");
 }else{ 
      out.write("\n");
      out.write("\t\t\t\t\t\t<input type=\"submit\" value=\"SPEGNI\" formmethod=\"post\" style=\"color: darkred\">\n");
      out.write("\t\t\t\t\t");
 } 
      out.write("\n");
      out.write("\t\t\t \t\t<input type=\"submit\" value=\"DIMMER+\" formaction=\"switch1DIMMER\" formmethod=\"post\" style=\"color: black\">\t\t\n");
      out.write("\t\t\t \t\t<input type=\"submit\" value=\"DIMMER-\" formaction=\"switch1DIMMER\" formmethod=\"get\" style=\"color: black\">\n");
      out.write("\t\t\t \t\t<input type=\"submit\" value=\"RINOMINA\" formaction=\"rinomina1\" formmethod=\"get\" style=\"color: teal\">\n");
      out.write("\t\t\t \t");
 } 
      out.write("\n");
      out.write("\t\t\t</form>\n");
      out.write("\t\t\t<br><br>\n");
      out.write("\t\t\t<form action=\"switch2IO\" method =\"post\">\n");
      out.write("\t\t\t\t<b><label style=\"color: white\">SWITCH 2: </label></b>\n");
      out.write("\t\t\t\t");
 if(Controller.getSwitch2().withName()==0) { 
      out.write("\n");
      out.write("\t\t\t\t\t<input type=\"text\" name=\"sw2\" required>\n");
      out.write("\t\t\t\t\t<input type=\"submit\" value=\"ASSEGNA\" formaction=\"rinomina2\" formmethod=\"post\">\n");
      out.write("\t\t\t\t\t<input type=\"submit\" value=\"On/Off\" disabled>\t\n");
      out.write("\t\t\t \t\t<input type=\"submit\" value=\"DIMMER+\" disabled>\t\t\n");
      out.write("\t\t\t \t\t<input type=\"submit\" value=\"DIMMER-\" disabled>\n");
      out.write("\t\t\t \t\t<input type=\"submit\" value=\"RINOMINA\" disabled>\n");
      out.write("\t\t\t \t");
 }else{ 
      out.write("\n");
      out.write("\t\t\t \t\t<label style=\"color: orange; font-weight: bold; font-style: italic;\">");
      out.print( Controller.getSwitch2().getName().toUpperCase() );
      out.write("</label>\n");
      out.write("\t\t\t\t\t<input type=\"submit\" value=\"ASSEGNA\" disabled>\n");
      out.write("\t\t\t\t\t");
 if(Controller.getSwitch2().getStatus()==0) { 
      out.write("\n");
      out.write("\t\t\t\t\t\t<input type=\"submit\" value=\"ACCENDI\" formmethod=\"post\" style=\"color: darkgreen\">\n");
      out.write("\t\t\t\t\t");
 }else{ 
      out.write("\n");
      out.write("\t\t\t\t\t\t<input type=\"submit\" value=\"SPEGNI\" formmethod=\"post\" style=\"color: darkred\">\n");
      out.write("\t\t\t\t\t");
 } 
      out.write("\n");
      out.write("\t\t\t \t\t<input type=\"submit\" value=\"DIMMER+\" formaction=\"switch2DIMMER\" formmethod=\"post\" style=\"color: black\">\t\t\n");
      out.write("\t\t\t \t\t<input type=\"submit\" value=\"DIMMER-\" formaction=\"switch2DIMMER\" formmethod=\"get\" style=\"color: black\">\n");
      out.write("\t\t\t \t\t<input type=\"submit\" value=\"RINOMINA\" formaction=\"rinomina2\" formmethod=\"get\" style=\"color: teal\">\n");
      out.write("\t\t\t \t");
 } 
      out.write("\n");
      out.write("\t\t\t</form>\n");
      out.write("\t\t\t<br><br>\n");
      out.write("\t\t\t<form action=\"switch3IO\" method =\"post\">\n");
      out.write("\t\t\t\t<b><label style=\"color: white\">SWITCH 3: </label></b>\n");
      out.write("\t\t\t\t");
 if(Controller.getSwitch3().withName()==0) { 
      out.write("\n");
      out.write("\t\t\t\t\t<input type=\"text\" name=\"sw3\" required>\n");
      out.write("\t\t\t\t\t<input type=\"submit\" value=\"ASSEGNA\" formaction=\"rinomina3\" formmethod=\"post\">\n");
      out.write("\t\t\t\t\t<input type=\"submit\" value=\"On/Off\" disabled>\t\n");
      out.write("\t\t\t \t\t<input type=\"submit\" value=\"DIMMER+\" disabled>\t\t\n");
      out.write("\t\t\t \t\t<input type=\"submit\" value=\"DIMMER-\" disabled>\n");
      out.write("\t\t\t \t\t<input type=\"submit\" value=\"RINOMINA\" disabled>\n");
      out.write("\t\t\t \t");
 }else{ 
      out.write("\n");
      out.write("\t\t\t \t\t<label style=\"color: orange; font-weight: bold; font-style: italic;\">");
      out.print(Controller.getSwitch3().getName().toUpperCase());
      out.write("</label>\n");
      out.write("\t\t\t\t\t<input type=\"submit\" value=\"ASSEGNA\" disabled>\n");
      out.write("\t\t\t\t\t");
 if(Controller.getSwitch3().getStatus()==0) { 
      out.write("\n");
      out.write("\t\t\t\t\t\t<input type=\"submit\" value=\"ACCENDI\" formmethod=\"post\" style=\"color: darkgreen\">\n");
      out.write("\t\t\t\t\t");
 }else{ 
      out.write("\n");
      out.write("\t\t\t\t\t\t<input type=\"submit\" value=\"SPEGNI\" formmethod=\"post\" style=\"color: darkred\">\n");
      out.write("\t\t\t\t\t");
 } 
      out.write("\n");
      out.write("\t\t\t \t\t<input type=\"submit\" value=\"DIMMER+\" formaction=\"switch3DIMMER\" formmethod=\"post\" style=\"color: black\">\t\t\n");
      out.write("\t\t\t \t\t<input type=\"submit\" value=\"DIMMER-\" formaction=\"switch3DIMMER\" formmethod=\"get\" style=\"color: black\">\n");
      out.write("\t\t\t \t\t<input type=\"submit\" value=\"RINOMINA\" formaction=\"rinomina3\" formmethod=\"get\" style=\"color: teal\">\n");
      out.write("\t\t\t \t");
 } 
      out.write("\n");
      out.write("\t\t\t</form>  \n");
      out.write("\t\t\t<br><br>\n");
      out.write("\t\t\t<form action=\"switch4IO\" method =\"post\">\n");
      out.write("\t\t\t\t<b><label style=\"color: white\">SWITCH 4: </label></b>\n");
      out.write("\t\t\t\t");
 if(Controller.getSwitch4().withName()==0) { 
      out.write("\n");
      out.write("\t\t\t\t\t<input type=\"text\" name=\"sw4\" required>\n");
      out.write("\t\t\t\t\t<input type=\"submit\" value=\"ASSEGNA\" formaction=\"rinomina4\" formmethod=\"post\">\n");
      out.write("\t\t\t\t\t<input type=\"submit\" value=\"On/Off\" disabled>\t\n");
      out.write("\t\t\t \t\t<input type=\"submit\" value=\"DIMMER+\" disabled>\t\t\n");
      out.write("\t\t\t \t\t<input type=\"submit\" value=\"DIMMER-\" disabled>\n");
      out.write("\t\t\t \t\t<input type=\"submit\" value=\"RINOMINA\" disabled>\n");
      out.write("\t\t\t \t");
 }else{ 
      out.write("\n");
      out.write("\t\t\t \t\t<label style=\"color: orange; font-weight: bold; font-style: italic;\">");
      out.print(Controller.getSwitch4().getName().toUpperCase());
      out.write("</label>\n");
      out.write("\t\t\t\t\t<input type=\"submit\" value=\"ASSEGNA\" formmethod=\"get\" disabled>\n");
      out.write("\t\t\t\t\t");
 if(Controller.getSwitch4().getStatus()==0) {
      out.write("\n");
      out.write("\t\t\t\t\t\t<input type=\"submit\" value=\"ACCENDI\" formmethod=\"post\" style=\"color: darkgreen\">\n");
      out.write("\t\t\t\t\t");
} else {
      out.write("\n");
      out.write("\t\t\t\t\t\t<input type=\"submit\" value=\"SPEGNI\" formmethod=\"post\" style=\"color: darkred\">\n");
      out.write("\t\t\t\t\t");
 } 
      out.write("\n");
      out.write("\t\t\t \t\t<input type=\"submit\" value=\"DIMMER+\" formaction=\"switch4DIMMER\" formmethod=\"post\" style=\"color: black\">\t\t\n");
      out.write("\t\t\t \t\t<input type=\"submit\" value=\"DIMMER-\" formaction=\"switch4DIMMER\" formmethod=\"get\" style=\"color: black\">\n");
      out.write("\t\t\t \t\t<input type=\"submit\" value=\"RINOMINA\" formaction=\"rinomina4\" formmethod=\"get\" style=\"color: teal\">\n");
      out.write("\t\t\t \t");
} 
      out.write("\n");
      out.write("\t\t\t</form>\n");
      out.write("\t\t\t<br><br>\n");
      out.write("\t\t\t<form action = \"chiudiSocket\" method = \"post\">\n");
      out.write("\t\t\t\t<input type=\"submit\" value=\"RINOMINA CONTROLLER\" formaction=\"homePage\" formmethod=\"get\" style=\"color: teal\">\n");
      out.write("\t\t\t\t<input type=\"submit\" value=\"TERMINA CONNESSIONE\" formmethod=\"post\" style=\"color: red\">\n");
      out.write("\t\t\t</form>\n");
      out.write("\t\t</div> \n");
      out.write("\t</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
